/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISAO;

import MODELO.Eleitor;
import URNA.Urna;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author lucas
 */
public class TelaLogin extends javax.swing.JFrame {
    public Urna instancia=null;
    
     /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        System.out.println("Chamou o Construtor Errado");
    }
    
  /**
   * 
   * @param instancia Urna
   */
    public TelaLogin(Urna instancia) {
        this.instancia=instancia;
        // Pega Dados do Google Drive
        System.out.println("Baixando dados da Nuvem");
        this.instancia.Receive();
        //Inicializando a Tela
        System.out.println("Inicializando a urna");
        initComponents();
        this.setVisible(true);
        this.instancia.setTelaVisivel(true);   
        this.setTitle("Login");
    }
    
    public void setTelaVisivel(boolean arg){
        this.instancia.setTelaVisivel(arg);
    }
    public boolean getTelaVisivel(){
        return instancia.getTelaVisivel();
    }
    public boolean getLogado(){
        return instancia.getLogado();
    }
    public Eleitor getUser(){
        return instancia.getUser();
                
    }
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextPath = new javax.swing.JTextField();
        ButtonCarregar = new javax.swing.JToggleButton();
        ButtonLogar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TextPath.setEnabled(false);
        TextPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextPathActionPerformed(evt);
            }
        });

        ButtonCarregar.setText("Carregar");
        ButtonCarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCarregarActionPerformed(evt);
            }
        });

        ButtonLogar.setText("Logar");
        ButtonLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLogarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ButtonLogar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TextPath, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(ButtonCarregar)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonCarregar))
                .addGap(31, 31, 31)
                .addComponent(ButtonLogar)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonCarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCarregarActionPerformed
       //Logar
       //Endereço que vai começar a pesquisar
		System.out.println("Localizando Imagem");
		String pathInicial="/home/lucas/Área de Trabalho/TrabalhoPoo/Arquivos PPM/";
		JFileChooser arquivo = new JFileChooser(pathInicial);
		arquivo.setFileFilter(new FileNameExtensionFilter("Image files", "ppm"));
		arquivo.setAcceptAllFileFilterUsed(false);
		arquivo.showOpenDialog(null);
		File file = arquivo.getSelectedFile();
		if(file!=null) {
			System.out.println("Arquivo Localizado");
			String caminho = file.getAbsolutePath();
			TextPath.setText(caminho);
		}	
    }//GEN-LAST:event_ButtonCarregarActionPerformed

    private void ButtonLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLogarActionPerformed
       // Faz login
		if (TextPath.getText().length() <= 0) {
			System.out.println("Não Há caminho para o arquivo");
			JOptionPane.showMessageDialog(this, "Abra o arquivo");
		} else {
			// Verifica se a senha é igual
			System.out.println("Verificando a Senha");
                        System.out.println(instancia);
			Eleitor elei=instancia.Login(TextPath.getText());
			//Se for igual chama Console.Urna
			if (elei != null) {
                            new ConsoleUrna(instancia,elei,elei.getUrnaVotacao());
                            instancia.setTelaVisivel(false);
                            this.setVisible(false);
                            this.dispose();//CULPADO                         
			} else {
				JOptionPane.showMessageDialog(this, "Senha Incorreta");
			}
		}
    }//GEN-LAST:event_ButtonLogarActionPerformed

    private void TextPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextPathActionPerformed

    /*

    public static void main(String args[]) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton ButtonCarregar;
    private javax.swing.JToggleButton ButtonLogar;
    private javax.swing.JTextField TextPath;
    // End of variables declaration//GEN-END:variables
}
