/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISAO;
import CENTRAL.Central;
import MODELO.*;
import DAO.*;
import java.io.File;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author lucas
 */
public class TelaCentral extends javax.swing.JFrame {
    private String Path="";
    private Central instancia=null;
    /**
     * Creates new form NewJFrame
     */
    public TelaCentral() {
        initComponents();
    }
    public TelaCentral(Central central) {
        this.instancia=central;
        initComponents();
        this.setTitle("Central");
        //Ficas esteticamente bonito
        ListLabelCPF.setText("");
        ListLabelNumero.setText("");
        ListLabelNome.setText("");
        ListLabelNVotos.setText("");
        ListLabelNomePartido.setText("");
        ListLabelNumeroPartido.setText("");
        
        //Chama os 3 Resultados
        instancia.Resultado();

        //Tabela
        //Zera a Tabela
        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Eleitor", "Candidato", "Partido"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });

        //Preenche a tabela
        DefaultTableModel model = (DefaultTableModel) Tabela.getModel();
        for (int i = 0; i < instancia.TotalVotos();i++) {
            Voto v= instancia.VotoIndice(i);
            if(v!=null){
                String eName= v.getEleitor().getNome();
                String cName= v.getCandidato().getNome();
                String pName= v.getCandidato().getPartido().getNome();
                Object[] linha ={eName,cName,pName};
                model.addRow(linha);
            }
        }
        jScrollPane3.setViewportView(Tabela);
        //Lista
        DefaultListModel<String> listModel = new DefaultListModel<>();
        for (int i = 0; i < instancia.TotalCandidatos(); i++) {
            listModel.addElement(instancia.CandidatoIndice(i).getNome());
        }
        jList3.setModel(listModel);
        jScrollPane5.setViewportView(jList3);
        jList3.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Panel = new javax.swing.JTabbedPane();
        PanelEleitor = new javax.swing.JLayeredPane();
        EleitorButaoCriar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        EleitorCampoNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        EleitorCampoTitulo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        EleitorCampoCPF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        EleitorCampoUrna = new javax.swing.JTextField();
        Eleitor = new javax.swing.JLabel();
        Carregar = new javax.swing.JToggleButton();
        PanelCandidato = new javax.swing.JLayeredPane();
        CandidatoButaoCriar1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        CandidatoCampoNome = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        CandidatoCampoNumero = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        CandidatoCampoCPF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        CandidatoCampoPartido = new javax.swing.JTextField();
        Candidato = new javax.swing.JLabel();
        PanelPartido = new javax.swing.JLayeredPane();
        PartidoButaoCriar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        PartidoCampoNome = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        PartidoCampoNumero = new javax.swing.JTextField();
        Partido = new javax.swing.JLabel();
        PanelVotos = new javax.swing.JLayeredPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        PanelResultado = new javax.swing.JLayeredPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        ListLabelNome = new javax.swing.JLabel();
        ListLabelNumeroPartido = new javax.swing.JLabel();
        ListLabelCPF = new javax.swing.JLabel();
        ListLabelNomePartido = new javax.swing.JLabel();
        ListLabelNumero = new javax.swing.JLabel();
        ListLabelNVotos = new javax.swing.JLabel();
        PanelVencedor = new javax.swing.JLayeredPane();
        resultadoTxt = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        VencedorTxt = new javax.swing.JTextArea();

        jLabel4.setText("jLabel1");

        jTextField3.setText("jTextField1");

        jLabel9.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                PanelAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        Panel.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                PanelStateChanged(evt);
            }
        });

        EleitorButaoCriar.setText("Criar");
        EleitorButaoCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EleitorButaoCriarActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome Eleitor");

        EleitorCampoNome.setText("Digite...");
        EleitorCampoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EleitorCampoNomeActionPerformed(evt);
            }
        });

        jLabel3.setText("Titulo de Eleitor");

        EleitorCampoTitulo.setText("Digite...");
        EleitorCampoTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EleitorCampoTituloActionPerformed(evt);
            }
        });

        jLabel5.setText("CPF - Cadastro de Pessoa Física");

        EleitorCampoCPF.setText("Digite...");
        EleitorCampoCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EleitorCampoCPFActionPerformed(evt);
            }
        });

        jLabel6.setText("Numero da Urna de Votacao");

        EleitorCampoUrna.setText("Digite...");

        Eleitor.setText("Dados Cadastrados");

        Carregar.setText("Carregar Imagem");
        Carregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarregarActionPerformed(evt);
            }
        });

        PanelEleitor.setLayer(EleitorButaoCriar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PanelEleitor.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PanelEleitor.setLayer(EleitorCampoNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PanelEleitor.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PanelEleitor.setLayer(EleitorCampoTitulo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PanelEleitor.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PanelEleitor.setLayer(EleitorCampoCPF, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PanelEleitor.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PanelEleitor.setLayer(EleitorCampoUrna, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PanelEleitor.setLayer(Eleitor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PanelEleitor.setLayer(Carregar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout PanelEleitorLayout = new javax.swing.GroupLayout(PanelEleitor);
        PanelEleitor.setLayout(PanelEleitorLayout);
        PanelEleitorLayout.setHorizontalGroup(
            PanelEleitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEleitorLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(PanelEleitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(PanelEleitorLayout.createSequentialGroup()
                        .addGroup(PanelEleitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EleitorCampoNome)
                            .addComponent(jLabel3)
                            .addComponent(EleitorCampoTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                            .addComponent(jLabel6)
                            .addComponent(EleitorCampoUrna, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                            .addComponent(jLabel5)
                            .addComponent(EleitorCampoCPF, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                            .addComponent(Eleitor, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(118, 118, 118)
                        .addComponent(Carregar, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(135, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEleitorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EleitorButaoCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
        PanelEleitorLayout.setVerticalGroup(
            PanelEleitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEleitorLayout.createSequentialGroup()
                .addComponent(EleitorButaoCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelEleitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelEleitorLayout.createSequentialGroup()
                        .addComponent(EleitorCampoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EleitorCampoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EleitorCampoCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EleitorCampoUrna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Carregar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Eleitor, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        Panel.addTab("Eleitor", PanelEleitor);

        CandidatoButaoCriar1.setText("Criar");
        CandidatoButaoCriar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CandidatoButaoCriar1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome candidato");

        CandidatoCampoNome.setText("Digite...");

        jLabel7.setText("Numero");

        CandidatoCampoNumero.setText("Digite...");
        CandidatoCampoNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CandidatoCampoNumeroActionPerformed(evt);
            }
        });

        jLabel8.setText("CPF - Cadastro de Pessoa Física");

        CandidatoCampoCPF.setText("Digite...");
        CandidatoCampoCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CandidatoCampoCPFActionPerformed(evt);
            }
        });

        jLabel10.setText("Partido");

        CandidatoCampoPartido.setText("Digite...");

        Candidato.setText("Dados Cadastrados");

        PanelCandidato.setLayer(CandidatoButaoCriar1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PanelCandidato.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PanelCandidato.setLayer(CandidatoCampoNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PanelCandidato.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PanelCandidato.setLayer(CandidatoCampoNumero, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PanelCandidato.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PanelCandidato.setLayer(CandidatoCampoCPF, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PanelCandidato.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PanelCandidato.setLayer(CandidatoCampoPartido, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PanelCandidato.setLayer(Candidato, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout PanelCandidatoLayout = new javax.swing.GroupLayout(PanelCandidato);
        PanelCandidato.setLayout(PanelCandidatoLayout);
        PanelCandidatoLayout.setHorizontalGroup(
            PanelCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCandidatoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(PanelCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(PanelCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(CandidatoCampoNome)
                        .addComponent(jLabel7)
                        .addComponent(CandidatoCampoNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addComponent(CandidatoCampoPartido, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addComponent(CandidatoCampoCPF, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                        .addComponent(Candidato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(424, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCandidatoLayout.createSequentialGroup()
                .addContainerGap(477, Short.MAX_VALUE)
                .addComponent(CandidatoButaoCriar1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
        PanelCandidatoLayout.setVerticalGroup(
            PanelCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCandidatoLayout.createSequentialGroup()
                .addComponent(CandidatoButaoCriar1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CandidatoCampoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CandidatoCampoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CandidatoCampoCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CandidatoCampoPartido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Candidato, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        Panel.addTab("Candidato", PanelCandidato);

        PartidoButaoCriar.setText("Criar");
        PartidoButaoCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PartidoButaoCriarActionPerformed(evt);
            }
        });

        jLabel13.setText("Nome Partido");

        PartidoCampoNome.setText("Digite...");

        jLabel14.setText("Numero Partido");

        PartidoCampoNumero.setText("Digite...");
        PartidoCampoNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PartidoCampoNumeroActionPerformed(evt);
            }
        });

        Partido.setText("Dados Cadastrados");

        PanelPartido.setLayer(PartidoButaoCriar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PanelPartido.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PanelPartido.setLayer(PartidoCampoNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PanelPartido.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PanelPartido.setLayer(PartidoCampoNumero, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PanelPartido.setLayer(Partido, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout PanelPartidoLayout = new javax.swing.GroupLayout(PanelPartido);
        PanelPartido.setLayout(PanelPartidoLayout);
        PanelPartidoLayout.setHorizontalGroup(
            PanelPartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPartidoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(PanelPartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(PanelPartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(PartidoCampoNome)
                        .addComponent(jLabel14)
                        .addComponent(PartidoCampoNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                        .addComponent(Partido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(424, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPartidoLayout.createSequentialGroup()
                .addContainerGap(477, Short.MAX_VALUE)
                .addComponent(PartidoButaoCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
        PanelPartidoLayout.setVerticalGroup(
            PanelPartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPartidoLayout.createSequentialGroup()
                .addComponent(PartidoButaoCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PartidoCampoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PartidoCampoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Partido, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(255, Short.MAX_VALUE))
        );

        Panel.addTab("Partido", PanelPartido);

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Eleitor", "Candidato", "Partido"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(Tabela);

        PanelVotos.setLayer(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout PanelVotosLayout = new javax.swing.GroupLayout(PanelVotos);
        PanelVotos.setLayout(PanelVotosLayout);
        PanelVotosLayout.setHorizontalGroup(
            PanelVotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 823, Short.MAX_VALUE)
        );
        PanelVotosLayout.setVerticalGroup(
            PanelVotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
        );

        Panel.addTab("Tabela de Votos", PanelVotos);

        jList3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList3.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList3ValueChanged(evt);
            }
        });
        jScrollPane5.setViewportView(jList3);

        ListLabelNome.setText("Nome");

        ListLabelNumeroPartido.setText("Numero Partido");

        ListLabelCPF.setText("Cpf");

        ListLabelNomePartido.setText("Nome Partido");

        ListLabelNumero.setText("Numero");

        ListLabelNVotos.setText("Total de Votos");

        PanelResultado.setLayer(jScrollPane5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PanelResultado.setLayer(ListLabelNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PanelResultado.setLayer(ListLabelNumeroPartido, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PanelResultado.setLayer(ListLabelCPF, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PanelResultado.setLayer(ListLabelNomePartido, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PanelResultado.setLayer(ListLabelNumero, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PanelResultado.setLayer(ListLabelNVotos, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout PanelResultadoLayout = new javax.swing.GroupLayout(PanelResultado);
        PanelResultado.setLayout(PanelResultadoLayout);
        PanelResultadoLayout.setHorizontalGroup(
            PanelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelResultadoLayout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                .addGroup(PanelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelResultadoLayout.createSequentialGroup()
                        .addGroup(PanelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ListLabelCPF)
                            .addComponent(ListLabelNumero))
                        .addGap(216, 216, 216))
                    .addGroup(PanelResultadoLayout.createSequentialGroup()
                        .addGroup(PanelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ListLabelNome)
                            .addComponent(ListLabelNomePartido)
                            .addComponent(ListLabelNumeroPartido)
                            .addComponent(ListLabelNVotos))
                        .addContainerGap())))
        );
        PanelResultadoLayout.setVerticalGroup(
            PanelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
            .addGroup(PanelResultadoLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(ListLabelNome)
                .addGap(18, 18, 18)
                .addComponent(ListLabelNumero)
                .addGap(18, 18, 18)
                .addComponent(ListLabelCPF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ListLabelNomePartido)
                .addGap(24, 24, 24)
                .addComponent(ListLabelNumeroPartido)
                .addGap(18, 18, 18)
                .addComponent(ListLabelNVotos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Panel.addTab("Lista Candidatos com numero de Votos", PanelResultado);

        PanelVencedor.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                PanelVencedorComponentShown(evt);
            }
        });

        resultadoTxt.setText("Vencedor?");

        VencedorTxt.setEditable(false);
        VencedorTxt.setColumns(20);
        VencedorTxt.setRows(5);
        jScrollPane1.setViewportView(VencedorTxt);

        PanelVencedor.setLayer(resultadoTxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PanelVencedor.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout PanelVencedorLayout = new javax.swing.GroupLayout(PanelVencedor);
        PanelVencedor.setLayout(PanelVencedorLayout);
        PanelVencedorLayout.setHorizontalGroup(
            PanelVencedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVencedorLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(PanelVencedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelVencedorLayout.createSequentialGroup()
                        .addComponent(resultadoTxt)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelVencedorLayout.setVerticalGroup(
            PanelVencedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVencedorLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(resultadoTxt)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                .addContainerGap())
        );

        Panel.addTab("Vencedor", PanelVencedor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PanelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_PanelAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelAncestorAdded

    private void jList3ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList3ValueChanged
        int indice=jList3.getAnchorSelectionIndex();
        if(indice == -1){//Se nada foi selecionado
            ListLabelCPF.setText("CPF");
            ListLabelNVotos.setText("Total de Votos");
            ListLabelNome.setText("Nome Candidato");
            ListLabelNomePartido.setText("Nome Partido");
            ListLabelNumeroPartido.setText("Numero Partido");
            return;
        }else{//Se algo foi selecionado
            instancia.Resultado();//Atualiza vetor nVotos
            Candidato candidato=null;
            candidato=instancia.CandidatoIndice(indice);//Procura Candidato criado
            if(candidato!=null){
                ListLabelCPF.setText("CPF:"+candidato.getCpfString());
                ListLabelNumero.setText("Numero:"+candidato.getNumero());
                ListLabelNome.setText("Nome:"+candidato.getNome());
                ListLabelNVotos.setText("Numero de Votos:"+instancia.nVotoIndice(indice));
                Partido partido=null;
                partido=candidato.getPartido();
                if(partido != null){
                    ListLabelNomePartido.setText("Nome Partido:"+partido.getNome());
                    ListLabelNumeroPartido.setText("Numero Partido:"+partido.getNumero());
                }else{
                    JOptionPane.showMessageDialog(null, "Erro Partido Invalido");
                }
            }
        }
    }//GEN-LAST:event_jList3ValueChanged

    private void PartidoCampoNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PartidoCampoNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PartidoCampoNumeroActionPerformed

    private void PartidoButaoCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PartidoButaoCriarActionPerformed
        boolean validacao=false;
        String CampoNumeroPartido=PartidoCampoNumero.getText();
        String CampoNomePartido=PartidoCampoNome.getText();
        validacao=instancia.CadastrarPartido(CampoNumeroPartido, CampoNomePartido);
        if(validacao){
            instancia.Send();
            String DadosPartido="Numero: "+CampoNumeroPartido+
            "\nNome: "+CampoNomePartido;

            Partido.setText(DadosPartido);
        }

    }//GEN-LAST:event_PartidoButaoCriarActionPerformed

    private void CandidatoCampoCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CandidatoCampoCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CandidatoCampoCPFActionPerformed

    private void CandidatoCampoNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CandidatoCampoNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CandidatoCampoNumeroActionPerformed

    private void CandidatoButaoCriar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CandidatoButaoCriar1ActionPerformed
        boolean validacao=false;
        String CampoNomeCandidato=CandidatoCampoNome.getText();
        String CampoNumeroCandidato=CandidatoCampoNumero.getText();
        String CampoCPF=CandidatoCampoCPF.getText();
        String CampoPartido=CandidatoCampoPartido.getText();
        validacao = instancia.CadastrarCandidato(CampoPartido, CampoNomeCandidato, CampoNumeroCandidato, CampoCPF);
        if(validacao){
            instancia.Send();
            String DadosCandidato="Nome: "+CampoNomeCandidato+
            "\nNumero: "+CampoNumeroCandidato+
            "\nCPF: "+CampoCPF+
            "\nPartido: "+CampoPartido;
            Candidato.setText(DadosCandidato);
        }
    }//GEN-LAST:event_CandidatoButaoCriar1ActionPerformed

    private void CarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarregarActionPerformed
        //Pega o Caminho Da imagem
        System.out.println("Localizando Imagem");

        //este caminho é arbitrario  (ficava mais faci lde debugar)
        String pathInicial="/home/lucas/Área de Trabalho/TrabalhoPoo/Arquivos PPM/";
        JFileChooser arquivo = new JFileChooser(pathInicial);
        //limita o tipo de arquivo que pode ser aberto
        arquivo.setFileFilter(new FileNameExtensionFilter("Image files", "ppm"));
        arquivo.setAcceptAllFileFilterUsed(false);
        arquivo.showOpenDialog(null);
        File file= arquivo.getSelectedFile();
        //Verifica se foi possivel Abrir
        if(file!=null) {
            System.out.println("Arquivo Localizado");
            Path = file.getAbsolutePath();
            Carregar.setSelected(true);
            //Avisa que a imagem foi carregada
        }else{
            Path ="";
            Carregar.setSelected(false);
            //Avisa que a imagem não foi carregada
        }
    }//GEN-LAST:event_CarregarActionPerformed

    private void EleitorCampoCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EleitorCampoCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EleitorCampoCPFActionPerformed

    private void EleitorCampoTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EleitorCampoTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EleitorCampoTituloActionPerformed

    private void EleitorCampoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EleitorCampoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EleitorCampoNomeActionPerformed

    private void EleitorButaoCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EleitorButaoCriarActionPerformed
        //Pegando da tela e salvando em variaveis
        boolean validacao=false;
        if(Path.length()==0){
            JOptionPane.showMessageDialog(null,"Selecio a Imagem .ppm");
            return;
        }
        String CampoNome=EleitorCampoNome.getText();
        String CampoTitulo=EleitorCampoTitulo.getText();
        String CampoCPF=EleitorCampoCPF.getText();
        String CampoUrna=EleitorCampoUrna.getText();

        //Valida Nome
        if(CampoNome.length()==0){
            JOptionPane.showMessageDialog(null,"Digite o Nome");
            return;
        }

        //Valida Titulo
        if(CampoTitulo.length()==0){
            JOptionPane.showMessageDialog(null,"Digite o Titulo de Eleitor");
        }

        //Valida Urna
        int numero =0;
        try{
            numero= Integer.parseInt(CampoUrna);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Digita apenas numero no campo da Urna");
            return;
        }

        //Valida Cpf
        Documentos doc=new Documentos(CampoCPF);
        if(!doc.getValidCpf()){
            JOptionPane.showMessageDialog(null,"Digite um Cpf Valido");
            return;
        }

        validacao=instancia.CriarEleitor(this.Path, CampoNome, CampoTitulo, CampoCPF, CampoUrna);
        this.Path="";//Reseta o PAth
        if(validacao){
            instancia.Send();
            String DadosCadastrados="";
            DadosCadastrados="Nome: "+CampoNome+
            "\nTitulo: "+CampoTitulo+
            "\nCpf: "+CampoCPF+
            "\nUrna: "+CampoUrna;
            Eleitor.setText(DadosCadastrados);
        }
    }//GEN-LAST:event_EleitorButaoCriarActionPerformed

    private void PanelStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_PanelStateChanged

      
    }//GEN-LAST:event_PanelStateChanged

    private void PanelVencedorComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_PanelVencedorComponentShown
        int [] indiceVencedores = instancia.indiceVencedores();
        if(indiceVencedores==null){
            return;
        }
        if(indiceVencedores.length >1){
            resultadoTxt.setText("Empatou entre :");
            String vencedores="";
            for (int i = 0; i < indiceVencedores.length; i++) {
                vencedores+="\n"+instancia.CandidatoIndice(indiceVencedores[i]).getNome();       
            }
            VencedorTxt.setText(vencedores);    
        }else{
            resultadoTxt.setText("Vencedor foi:");
            Candidato vencedor=instancia.CandidatoIndice(indiceVencedores[0]);
            VencedorTxt.setText("\n"+vencedor.getNome());
        }      
    }//GEN-LAST:event_PanelVencedorComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCentral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCentral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCentral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCentral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCentral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Candidato;
    private javax.swing.JButton CandidatoButaoCriar1;
    private javax.swing.JTextField CandidatoCampoCPF;
    private javax.swing.JTextField CandidatoCampoNome;
    private javax.swing.JTextField CandidatoCampoNumero;
    private javax.swing.JTextField CandidatoCampoPartido;
    private javax.swing.JToggleButton Carregar;
    private javax.swing.JLabel Eleitor;
    private javax.swing.JButton EleitorButaoCriar;
    private javax.swing.JTextField EleitorCampoCPF;
    private javax.swing.JTextField EleitorCampoNome;
    private javax.swing.JTextField EleitorCampoTitulo;
    private javax.swing.JTextField EleitorCampoUrna;
    private javax.swing.JLabel ListLabelCPF;
    private javax.swing.JLabel ListLabelNVotos;
    private javax.swing.JLabel ListLabelNome;
    private javax.swing.JLabel ListLabelNomePartido;
    private javax.swing.JLabel ListLabelNumero;
    private javax.swing.JLabel ListLabelNumeroPartido;
    private javax.swing.JTabbedPane Panel;
    private javax.swing.JLayeredPane PanelCandidato;
    private javax.swing.JLayeredPane PanelEleitor;
    private javax.swing.JLayeredPane PanelPartido;
    private javax.swing.JLayeredPane PanelResultado;
    private javax.swing.JLayeredPane PanelVencedor;
    private javax.swing.JLayeredPane PanelVotos;
    private javax.swing.JLabel Partido;
    private javax.swing.JButton PartidoButaoCriar;
    private javax.swing.JTextField PartidoCampoNome;
    private javax.swing.JTextField PartidoCampoNumero;
    private javax.swing.JTable Tabela;
    private javax.swing.JTextArea VencedorTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel resultadoTxt;
    // End of variables declaration//GEN-END:variables
}
